sever:
  port: 8080

spring:
  application:
    name=WaguWagu

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false


